name: run trigger_test.py

on:
  schedule:
    - cron: "0 * * * *" # run per hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Debug - Show current working directory and files
        run: |
          echo "PWD: $(pwd)"
          ls -al

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run trigger_test.py
        run: python trigger_test.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
